let adminData, campus = 'Downcity', charts = [];
const colors = ['#8B9556','#6B7F5C','#9CAF88','#4A5240','#7F8C8D','#34495e','#333','#838383'];
document.addEventListener('DOMContentLoaded', async () => { const response = await fetch('data.json'); adminData = await response.json(); renderAdmin(); wireAdmin(); });

function renderAdmin() { destroyCharts(); const inventory = adminData.inventory.filter(item => item.campus === campus); renderCharts(inventory); totalCount(inventory); RetrievedTableLoader(); OpenTableLoader(); }
function renderCharts(items) {
  charts.push(new Chart(document.getElementById('generalBar'), { type:'bar', data:{labels:items.map(x=>x.model),datasets:[{data:items.map(x=>x.quantity),backgroundColor:colors}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}} }));
  [['Monitors','monitorsPie'],['Laptops','laptopsPie'],['Desktops','desktopsPie'],['Printers','printersPie']].forEach(([type,id]) => { const rows=items.filter(x=>x.delivery_type===type); charts.push(new Chart(document.getElementById(id),{type:'pie',data:{labels:rows.map(x=>x.model),datasets:[{data:rows.map(x=>x.quantity),backgroundColor:colors}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'right'}}}})); });
}
function totalCount(items) { document.querySelector('#allTable tbody').innerHTML = items.map(x=>`<tr><td class="tonerRows">${escapeHTML(x.model)}</td><td class="tonerRows">${x.quantity}</td></tr>`).join(''); }
function RetrievedTableLoader() { document.querySelector('#lastTable tbody').innerHTML = adminData.transactions.map(x=>`<tr><td>${x.quantity}</td><td>${escapeHTML(x.hardware_type)}</td><td>${escapeHTML(x.model)}</td><td>${escapeHTML(x.campus)}</td><td>${escapeHTML(x.staff)}</td><td>${escapeHTML(x.transfer_date)}</td></tr>`).join(''); }
function OpenTableLoader() { const counts = Object.values(adminData.open_equipment.reduce((all,x)=>{const key=x.eq_model+'|'+x.eq_type; all[key]??={quantity:0,model:x.eq_model,type:x.eq_type}; all[key].quantity++; return all;},{})); document.querySelector('#openTable tbody').innerHTML = counts.map(x=>`<tr><td>${x.quantity}</td><td>${escapeHTML(x.model)}</td><td>${escapeHTML(x.type)}</td></tr>`).join(''); }
function destroyCharts() { charts.forEach(chart=>chart.destroy()); charts=[]; }
function wireAdmin() { document.getElementById('campusToggle').addEventListener('change',e=>{campus=e.target.checked?'Harborside':'Downcity';renderAdmin();}); document.getElementById('themeToggle').addEventListener('change',e=>document.body.classList.toggle('dark-theme',e.target.checked)); document.getElementById('profileIcon').addEventListener('click',()=>document.getElementById('dropdown').classList.toggle('show')); document.getElementById('menuIcon').addEventListener('click',()=>document.getElementById('menudropdown').classList.toggle('show')); document.getElementById('export').addEventListener('click',exportCSV); }
function exportCSV() { const rows=[['Hardware Type','Model','Campus','Quantity'],...adminData.inventory.filter(x=>x.campus===campus).map(x=>[x.delivery_type,x.model,x.campus,x.quantity])]; const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'); const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`${campus.toLowerCase()}-inventory.csv`;link.click();URL.revokeObjectURL(link.href); }
function escapeHTML(value) { return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
